export const fakeData = [
  {
    fN: 'Christy',
    lN: 'Camacho',
    company: 'ANACHO',
    JTitle: 'Web Developer',
    email: '1@email.com',
    phone: '+1-202-555-0151',
  },
  {
    fN: 'Henderson',
    lN: 'Cambias',
    company: 'ISOTRACK',
    JTitle: 'Web Developer',
    email: '1@email.com',
    phone: '+1-202-555-0151',
  },
  {
    fN: 'Blair',
    lN: 'ISOTRACK',
    company: 'KRAGGLE',
    JTitle: 'Web Developer',
    email: '1@email.com',
    phone: '+1-202-555-0151',
  },
  {
    fN: 'Velazquez',
    lN: 'Smethley',
    company: 'SKYBOLD',
    JTitle: 'Web Developer',
    email: '1@email.com',
    phone: '+1-202-555-0151',
  },
  {
    fN: 'Nancy',
    lN: 'Jaggers',
    company: 'ANACHO',
    JTitle: 'Web Developer',
    email: '1@email.com',
    phone: '+1-202-555-0151',
  },
  {
    fN: 'Fernandez',
    lN: 'Ortiz',
    company: 'KRAGGLE',
    JTitle: 'Web Developer',
    email: '1@email.com',
    phone: '+1-202-555-0151',
  },
  {
    fN: 'Marla',
    lN: 'Castro',
    company: 'ISOTRACK',
    JTitle: 'Web Developer',
    email: 'marlacastro@isotrack.com',
    phone: '+1 (983) 594-2639',
  },
  {
    fN: 'Marla',
    lN: 'Castro',
    company: 'ISOTRACK',
    JTitle: 'Web Developer',
    email: 'marlacastro@isotrack.com',
    phone: '+1 (983) 594-2639',
  },
];
